version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fintech_analytics
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=fintech_analytics
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs

volumes:
  mysql_data:
